import Link from "next/link";
import AppHeader from "@/components/AppHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "What is AI Visibility? The Complete Guide",
  description: "AI Visibility measures how often your brand appears in AI-generated answers from ChatGPT, Claude, Gemini, and Perplexity. Learn why it matters and how to improve it.",
  alternates: { canonical: "/resources/what-is-ai-visibility" },
  openGraph: { title: "What is AI Visibility?", description: "AI Visibility measures how often your brand appears in AI-generated answers. Learn why it matters.", url: "https://visibilityradar.ai/resources/what-is-ai-visibility", type: "article" },
};

export default function WhatIsAiVisibility() {
  return (
    <main className="min-h-screen bg-white">
      <AppHeader />
      <article className="pt-24 pb-20 px-6">
        <div className="mx-auto max-w-2xl">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-4 py-1.5">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wide">Resource</span>
          </div>
          <h1 className="text-4xl font-extrabold text-slate-900 mb-4 leading-tight">What is AI Visibility?</h1>
          <p className="text-lg text-slate-500 mb-10 leading-relaxed border-b border-slate-100 pb-10">
            AI Visibility measures how often and how prominently your brand appears in responses generated by AI assistants like ChatGPT, Claude, Gemini, and Perplexity.
          </p>

          <div className="space-y-8 text-slate-600 leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">Why AI Visibility Matters</h2>
              <p>When someone asks an AI assistant "what's the best CRM for startups?" or "recommend a luxury hotel in Istanbul", the AI produces a direct answer — not a list of search results. If your brand isn't in that answer, you've lost the customer before they even started browsing.</p>
              <p className="mt-3">AI assistants now handle hundreds of millions of queries per day. A growing share of those are purchase-intent queries where brand recommendations are made directly by the model. This makes AI Visibility one of the most important metrics in modern digital marketing.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">How It's Measured</h2>
              <p>AI Visibility is measured by sending a set of relevant queries to major AI models and tracking whether your brand appears in the responses. VisibilityRadar does this across 6 models simultaneously — Claude, GPT-4o, Gemini, Perplexity, Grok, and DeepSeek — and scores each on a 0–100 scale.</p>
              <div className="mt-4 rounded-xl border border-slate-100 bg-slate-50 p-5 space-y-2">
                {[["0–30", "Low", "red"], ["30–60", "Moderate", "amber"], ["60–100", "Strong", "emerald"]].map(([range, label, color]) => (
                  <div key={range} className="flex items-center gap-3">
                    <span className={`w-16 text-xs font-bold text-${color}-600`}>{range}</span>
                    <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold bg-${color}-50 text-${color}-700`}>{label}</span>
                  </div>
                ))}
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">AI Visibility vs. Traditional SEO</h2>
              <p>Traditional SEO gets your brand ranked on Google. AI Visibility gets your brand recommended by AI. They share some foundations — quality content, authoritative backlinks — but the mechanisms differ significantly.</p>
              <p className="mt-3">AI models don't crawl your site in real time. They work from training data: Wikipedia, review platforms, news articles, forums, and structured content. This means optimizing for AI visibility requires a different strategy than Google SEO.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">Key Factors That Influence AI Visibility</h2>
              <ul className="space-y-2">
                {["Wikipedia presence — AI models heavily weight Wikipedia as a trusted source", "Review platform coverage — G2, Trustpilot, TripAdvisor, Capterra", "FAQ and structured data — machine-readable content AI can extract", "Press and news mentions — authoritative media coverage", "Comparison content — appearing in 'X vs Y' articles"].map(item => (
                  <li key={item} className="flex gap-2">
                    <span className="text-indigo-400 flex-shrink-0 mt-1">→</span>
                    <span className="text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </section>

            <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-7 text-center">
              <p className="text-sm font-bold text-indigo-900 mb-1">Check your brand's AI Visibility score</p>
              <p className="text-xs text-indigo-600 mb-5">Free scan across 6 AI models. No signup required.</p>
              <Link href="/" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-bold text-white hover:bg-indigo-700 transition-all">
                Run Free Scan →
              </Link>
            </div>
          </div>
        </div>
      </article>
    </main>
  );
}
