import AppHeader from "@/components/AppHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "VisibilityRadar Terms of Service — the rules and conditions for using our AI brand visibility platform.",
  alternates: { canonical: "/terms" },
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <AppHeader />
      <main className="mx-auto max-w-3xl px-4 py-16">
        <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
          <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-slate-400 mb-8">Last updated: June 25, 2026</p>

          <div className="prose prose-slate max-w-none space-y-8 text-sm leading-relaxed text-slate-600">

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using VisibilityRadar (&quot;the Service&quot;) at visibilityradar.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
              <p className="mt-2">These Terms apply to all visitors, users, and others who access or use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">2. Description of Service</h2>
              <p>VisibilityRadar is an AI brand visibility intelligence platform that measures how your brand appears across multiple AI language models including Claude, GPT-4o, Gemini, Perplexity, Grok, and DeepSeek. The Service provides:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>AI visibility scoring and analysis</li>
                <li>Competitor comparison reports</li>
                <li>Per-model strategy playbooks</li>
                <li>Brand sentiment analysis</li>
                <li>Downloadable PDF reports</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">3. Account Registration</h2>
              <p>To access certain features of the Service, you must create an account. You agree to:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Provide accurate, current, and complete information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Accept responsibility for all activities that occur under your account</li>
                <li>Notify us immediately of any unauthorized use of your account</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">4. Subscription Plans and Billing</h2>
              <p>VisibilityRadar offers the following plans:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>Free:</strong> 1 analysis per month, 2 AI models</li>
                <li><strong>Pro:</strong> 10 analyses per month, all 6 AI models — $49/month (launch pricing)</li>
                <li><strong>Agency:</strong> Unlimited analyses, all 6 AI models, API access — $599/month</li>
              </ul>
              <p className="mt-3">Subscriptions are billed monthly. You may cancel at any time. Refunds are not provided for partial billing periods. Prices are subject to change with 30 days notice.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">5. Acceptable Use</h2>
              <p>You agree not to use the Service to:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe the intellectual property rights of others</li>
                <li>Submit false, misleading, or inaccurate brand information</li>
                <li>Attempt to reverse engineer or circumvent the Service</li>
                <li>Use the Service for competitive intelligence to build a competing product</li>
                <li>Share account access with unauthorized parties</li>
                <li>Abuse the API or make excessive automated requests</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">6. Intellectual Property</h2>
              <p>The Service and its original content, features, and functionality are and will remain the exclusive property of VisibilityRadar. Our trademarks and trade dress may not be used without our prior written consent.</p>
              <p className="mt-2">Reports generated by the Service based on your brand data are yours to use commercially. However, the underlying algorithms, prompts, and scoring methodology remain our intellectual property.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">7. Data and Privacy</h2>
              <p>Your use of the Service is also governed by our <a href="/privacy" className="text-indigo-600 hover:underline">Privacy Policy</a>, which is incorporated into these Terms by reference. By using the Service, you consent to our data practices as described in the Privacy Policy.</p>
              <p className="mt-2">You retain ownership of any brand data you submit to the Service. We may use aggregated, anonymized data to improve our services.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">8. Disclaimer of Warranties</h2>
              <p>The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any kind. We do not warrant that:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>The Service will be uninterrupted or error-free</li>
                <li>AI model responses reflect real-time or future behavior</li>
                <li>Visibility scores guarantee business outcomes</li>
                <li>Results from third-party AI models are accurate or up to date</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">9. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, VisibilityRadar shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, data loss, or business interruption, resulting from your use of the Service.</p>
              <p className="mt-2">Our total liability to you for any claims arising from these Terms or use of the Service shall not exceed the amount you paid us in the 3 months preceding the claim.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">10. Termination</h2>
              <p>We may terminate or suspend your account immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, third parties, or the public.</p>
              <p className="mt-2">Upon termination, your right to use the Service ceases immediately. You may export your data within 30 days of termination.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">11. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will notify you of significant changes via email or a prominent notice on the Service. Continued use of the Service after changes constitutes your acceptance of the new Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3">12. Contact</h2>
              <p>For questions about these Terms, please contact us at <a href="/contact" className="text-indigo-600 hover:underline">our contact page</a> or email <a href="mailto:legal@visibilityradar.ai" className="text-indigo-600 hover:underline">legal@visibilityradar.ai</a>.</p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
