import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { generateRecommendationsPdfBuffer } from '@/lib/generatePdfBuffer'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

interface Recommendation {
  title: string
  priority: 'high' | 'medium' | 'low'
  category: string
  description: string
  actions: string[]
}

interface ReportPayload {
  email: string
  brand: string
  overall_score: number
  market: string
  recommendations: Recommendation[]
  model_scores: Record<string, number>
}

function buildEmailHtml(payload: ReportPayload): string {
  const { brand, overall_score, market, recommendations, model_scores } = payload
  const scoreColor = overall_score >= 70 ? '#059669' : overall_score >= 40 ? '#d97706' : '#dc2626'

  const recsHtml = recommendations.map((rec, i) => `
    <tr>
      <td style="padding:16px;border-bottom:1px solid #f1f5f9;">
        <div style="display:flex;align-items:flex-start;gap:12px;">
          <div style="flex-shrink:0;width:24px;height:24px;border-radius:50%;background:#1e293b;color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;text-align:center;line-height:24px;">
            ${i + 1}
          </div>
          <div>
            <p style="margin:0 0 4px;font-size:14px;font-weight:600;color:#1e293b;">${rec.title}</p>
            <p style="margin:0 0 8px;font-size:12px;color:#64748b;">${rec.description}</p>
            <ol style="margin:0;padding-left:16px;">
              ${rec.actions.map(a => `<li style="font-size:12px;color:#475569;margin-bottom:4px;">${a}</li>`).join('')}
            </ol>
          </div>
        </div>
      </td>
    </tr>
  `).join('')

  const modelRows = Object.entries(model_scores).map(([model, score]) => `
    <tr>
      <td style="padding:8px 16px;font-size:13px;color:#475569;">${model}</td>
      <td style="padding:8px 16px;font-size:13px;font-weight:700;color:#1e293b;text-align:right;">${score.toFixed(0)}/100</td>
    </tr>
  `).join('')

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08);">

        <!-- Header -->
        <tr><td style="background:linear-gradient(135deg,#1e1b4b,#1e293b);padding:40px 40px 32px;">
          <p style="margin:0 0 4px;font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#818cf8;">VisibilityRadar · AI Brand Intelligence</p>
          <h1 style="margin:0 0 8px;font-size:26px;font-weight:800;color:#fff;">Your AI Visibility Playbook</h1>
          <p style="margin:0;font-size:14px;color:#94a3b8;">Personalized growth strategy for <strong style="color:#e2e8f0;">${brand}</strong> · ${market.toUpperCase()} market</p>
        </td></tr>

        <!-- Score banner -->
        <tr><td style="padding:24px 40px;border-bottom:1px solid #f1f5f9;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td>
                <p style="margin:0 0 2px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#94a3b8;">Overall AI Score</p>
                <p style="margin:0;font-size:48px;font-weight:900;color:${scoreColor};line-height:1;">${overall_score.toFixed(0)}<span style="font-size:20px;color:#94a3b8;">/100</span></p>
              </td>
              <td align="right" valign="top">
                <table cellpadding="0" cellspacing="0">
                  ${modelRows}
                </table>
              </td>
            </tr>
          </table>
        </td></tr>

        <!-- Recommendations -->
        <tr><td style="padding:24px 40px 8px;">
          <p style="margin:0 0 16px;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#94a3b8;">Your Action Plan — ${recommendations.length} Recommendations</p>
        </td></tr>
        <tr><td>
          <table width="100%" cellpadding="0" cellspacing="0">
            ${recsHtml}
          </table>
        </td></tr>

        <!-- Footer -->
        <tr><td style="padding:32px 40px;text-align:center;border-top:1px solid #f1f5f9;">
          <p style="margin:0 0 4px;font-size:12px;color:#94a3b8;">Generated by VisibilityRadar · Powered by Claude</p>
          <p style="margin:0;font-size:11px;color:#cbd5e1;">visibilityradar.ai</p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`
}

export async function POST(req: Request) {
  const payload: ReportPayload = await req.json()

  // Save lead to Supabase
  const { error: leadError } = await supabase.from('leads').insert({
    email: payload.email,
    brand: payload.brand,
    overall_score: payload.overall_score,
    market: payload.market,
    source: 'recommendation_panel',
  })
  if (leadError) console.error('[send-report] lead insert error:', leadError.message)

  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    // No email service configured — still return success so UI shows confirmation
    console.log(`[send-report] No RESEND_API_KEY — would send to ${payload.email}`)
    return NextResponse.json({ ok: true, note: 'email service not configured' })
  }

  const [html, pdfBuffer] = await Promise.all([
    Promise.resolve(buildEmailHtml(payload)),
    generateRecommendationsPdfBuffer(
      payload.brand,
      payload.overall_score,
      payload.market,
      payload.model_scores,
      payload.recommendations
    ),
  ])

  const pdfBase64 = pdfBuffer.toString('base64')
  const fileName = `VisibilityRadar_${payload.brand.replace(/[^a-zA-Z0-9]/g, '_')}_Playbook.pdf`

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'VisibilityRadar <reports@visibilityradar.ai>',
      to: [payload.email],
      subject: `Your AI Visibility Playbook — ${payload.brand}`,
      html,
      attachments: [
        {
          filename: fileName,
          content: pdfBase64,
        },
      ],
    }),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    console.error('[send-report] Resend error:', err)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }

  return NextResponse.json({ ok: true })
}
