"use client"

import { useState } from "react"
import Link from "next/link"
import AppHeader from "@/components/AppHeader"
import { useRouter } from "next/navigation"

const FAQS = [
  {
    category: "General",
    icon: "💡",
    items: [
      {
        q: "What is VisibilityRadar?",
        a: "VisibilityRadar measures how often and how positively AI models (Claude, GPT-4o, Gemini, Perplexity, Grok, DeepSeek) mention your brand. You get an overall AI Visibility Score (0–100), per-model breakdowns, sentiment analysis, competitor comparison, and a model-specific strategy playbook.",
      },
      {
        q: "Why does my brand's AI visibility matter?",
        a: "AI models are increasingly how people discover brands, products, and services. When someone asks ChatGPT or Claude for a recommendation, brands with higher AI visibility get mentioned — brands with low visibility are invisible. GEO (Generative Engine Optimization) is the new SEO.",
      },
      {
        q: "How is the AI Visibility Score calculated?",
        a: "We send 5 brand-specific prompts to each active AI model and measure how often your brand appears in responses, how prominently it's featured, and whether the sentiment is positive, neutral, or negative. The scores are aggregated into a 0–100 scale per model and then combined into an overall score.",
      },
      {
        q: "How often should I run an analysis?",
        a: "We recommend monthly analyses to track trends. AI models update their training data periodically, so your score can change over time. Pro and Agency plans show month-over-month score changes automatically.",
      },
    ],
  },
  {
    category: "Plans & Pricing",
    icon: "💳",
    items: [
      {
        q: "What's included in the Free plan?",
        a: "The Free plan includes 1 analysis with 2 AI models (Claude and GPT-4o), basic score breakdown, and limited recommendations. It's great for a quick first look at your brand's AI visibility.",
      },
      {
        q: "What does Pro include?",
        a: "Pro gives you 10 analyses per month across all 6 AI models, competitor comparison (up to 3 brands), full sentiment analysis, AI Strategy Playbook, AI Content Studio (5 blog posts/month), PDF export, weekly email digest, and MCP API access.",
      },
      {
        q: "What does Agency include?",
        a: "Agency includes everything in Pro plus unlimited analyses, up to 5 competitors per analysis, custom prompt library (50 prompts), white-label PDF reports, priority support, and MCP API access with higher rate limits.",
      },
      {
        q: "Can I cancel anytime?",
        a: "Yes. You can cancel your subscription anytime from your Account Settings page. Your plan stays active until the end of the billing period — no partial refunds, no hidden fees.",
      },
      {
        q: "Do unused analyses roll over?",
        a: "No. Monthly analysis credits reset on the 1st of each month. We recommend scheduling regular analyses to get the most out of your plan.",
      },
    ],
  },
  {
    category: "Analysis & Results",
    icon: "📊",
    items: [
      {
        q: "Which AI models does VisibilityRadar test?",
        a: "We test Claude (Anthropic), GPT-4o (OpenAI), Gemini (Google), Perplexity, Grok (xAI), and DeepSeek. Free accounts get Claude and GPT-4o. Pro and Agency accounts get all 6.",
      },
      {
        q: "What is the AI Strategy Playbook?",
        a: "The Playbook is a model-specific action plan generated by AI. For each model that gave your brand a low score, you get specific tactics — like 'build a Wikipedia presence' for Claude or 'earn reviews on G2' for Perplexity. Each action is prioritized by impact.",
      },
      {
        q: "What is the AI Content Studio?",
        a: "Content Studio generates 5 SEO and GEO-optimized blog posts tailored to your brand and the prompts AI models use to discover it. The posts are designed to improve your brand's citation chances in AI responses over time.",
      },
      {
        q: "What is Site AI Optimization?",
        a: "Site AI Optimization runs a 10-point audit of your website — checking schema markup, brand density, meta tags, and other signals that AI models use to understand and trust your brand. Available on Pro and Agency plans.",
      },
      {
        q: "Why do some models return a score of 0?",
        a: "Some AI models (especially Gemini) have safety filters that avoid making direct brand comparisons. If a model declines to respond to brand-specific prompts, it may return a 0 score. This is a known limitation and we're continuously improving prompt strategies to minimize it.",
      },
      {
        q: "Can I compare my brand against competitors?",
        a: "Yes. Pro plans support up to 3 competitors per analysis, Agency plans support up to 5. You'll see side-by-side AI Visibility Scores, per-model breakdowns, and alerts when a competitor pulls ahead.",
      },
    ],
  },
  {
    category: "MCP & API",
    icon: "🔌",
    items: [
      {
        q: "What is MCP and how does it work with VisibilityRadar?",
        a: "MCP (Model Context Protocol) is an open standard that lets AI assistants like Claude Desktop, Cursor, and Windsurf use external tools. With the VisibilityRadar MCP server installed, you can analyze brands, check history, and compare competitors directly from your AI chat — no browser needed.",
      },
      {
        q: "How do I set up the MCP server?",
        a: "1. Go to Account Settings and generate an API key under 'MCP API Keys'. 2. Install the package with: npx visibilityradar-mcp. 3. Add the config to your Claude Desktop or Cursor settings file with your API key. Full instructions are shown in Account Settings.",
      },
      {
        q: "Does MCP use my existing analysis credits?",
        a: "Yes. Every analyze_brand call via MCP counts as one analysis and deducts from your monthly quota — exactly the same as running an analysis from the dashboard. Results are also saved to your dashboard automatically.",
      },
      {
        q: "What are the MCP rate limits?",
        a: "Pro: up to 5 analyses per day via MCP. Agency: up to 20 analyses per day via MCP. Monthly limits still apply.",
      },
      {
        q: "Is MCP available on the Free plan?",
        a: "No. MCP API access requires a Pro or Agency plan. You can upgrade at any time from the Pricing page.",
      },
    ],
  },
  {
    category: "Privacy & Security",
    icon: "🔒",
    items: [
      {
        q: "Do you store my brand analysis data?",
        a: "Yes, your analysis history is stored securely in our database so you can track trends over time and access past results from your dashboard. You own your data and can delete your account at any time.",
      },
      {
        q: "Is my API key secure?",
        a: "API keys are shown only once at creation and stored as a hash in our database. If you lose your key, you'll need to revoke it and create a new one. Never share your API key publicly.",
      },
      {
        q: "Do you send my data to third-party AI models?",
        a: "We send your brand name, market, and competitor names to AI models to generate responses — this is the core of the analysis. We do not send any personal user data to AI models. Our Privacy Policy covers this in detail.",
      },
    ],
  },
]

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="border-b border-slate-100 last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left flex items-start justify-between gap-4 py-4 hover:text-indigo-600 transition-colors"
      >
        <span className="text-sm font-semibold text-slate-800">{q}</span>
        <span className={`flex-shrink-0 mt-0.5 transition-transform duration-200 ${open ? 'rotate-45' : ''}`}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M12 5v14M5 12h14" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
        </span>
      </button>
      {open && (
        <p className="text-sm text-slate-500 leading-relaxed pb-4">{a}</p>
      )}
    </div>
  )
}

export default function FaqPage() {
  const router = useRouter()
  return (
    <main className="min-h-screen bg-slate-50">
      <AppHeader onLogoClick={() => router.push("/")} />

      <div className="mx-auto max-w-3xl px-4 sm:px-6 pt-24 pb-20">

        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white px-4 py-1.5 mb-5 shadow-sm">
            <span className="text-xs font-black text-indigo-600 uppercase tracking-widest">FAQ</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 mb-3 tracking-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-slate-500 max-w-lg mx-auto text-sm leading-relaxed">
            Everything you need to know about VisibilityRadar. Can't find your answer?{" "}
            <Link href="/contact" className="text-indigo-600 hover:underline font-semibold">Contact us →</Link>
          </p>
        </div>

        {/* FAQ sections */}
        <div className="space-y-6">
          {FAQS.map(section => (
            <div key={section.category} className="rounded-2xl border border-slate-200 bg-white p-6">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-lg">{section.icon}</span>
                <p className="text-xs font-bold uppercase tracking-widest text-slate-400">{section.category}</p>
              </div>
              <div>
                {section.items.map(item => (
                  <FaqItem key={item.q} q={item.q} a={item.a} />
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="mt-10 rounded-2xl border border-indigo-100 bg-indigo-50 p-8 text-center">
          <p className="text-sm font-bold text-indigo-900 mb-2">Still have questions?</p>
          <p className="text-xs text-indigo-600 mb-5">Our team typically replies within 24 hours on business days.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/contact" className="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-indigo-700 transition-all">
              Contact us →
            </Link>
            <Link href="/pricing" className="rounded-xl border border-indigo-200 bg-white px-5 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-50 transition-all">
              View pricing
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}
