import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// Topic rotation — never repeat the same topic back-to-back
const TOPICS = [
  { title: "What Is GEO Optimization and Why Every Brand Needs It in 2025", keywords: ["GEO optimization", "generative engine optimization", "AI search", "brand visibility"] },
  { title: "How AI Models Decide Which Brands to Mention (And How to Get Mentioned More)", keywords: ["AI brand mentions", "LLM brand visibility", "ChatGPT brand", "Claude brand mentions"] },
  { title: "Share of Voice in the Age of AI: A New Metric Every CMO Should Track", keywords: ["share of voice AI", "AI brand awareness", "LLM share of voice"] },
  { title: "Why Your Brand Might Be Invisible to ChatGPT, Gemini, and Claude", keywords: ["brand invisible AI", "AI visibility score", "LLM brand recognition"] },
  { title: "The Complete Guide to LLM SEO: Ranking in AI Answers Instead of Search Results", keywords: ["LLM SEO", "AI search optimization", "rank in AI answers", "generative search"] },
  { title: "How to Measure Your Brand's AI Visibility: A Step-by-Step Framework", keywords: ["measure AI visibility", "AI brand score", "brand AI benchmark"] },
  { title: "ChatGPT vs Gemini vs Claude: Which AI Model Is Best for Brand Discovery?", keywords: ["ChatGPT brand discovery", "Gemini brand mentions", "Claude AI brand"] },
  { title: "Generative Engine Optimization (GEO): The SEO Strategy for the AI Era", keywords: ["generative engine optimization", "GEO strategy", "AI era SEO"] },
  { title: "How to Optimize Your Content to Appear in AI-Generated Answers", keywords: ["content optimization AI", "appear in AI answers", "LLM content strategy"] },
  { title: "Brand Sentiment in AI: Why Being Mentioned Isn't Enough", keywords: ["AI brand sentiment", "LLM brand perception", "AI brand analysis"] },
  { title: "The Hidden SEO War: How Top Brands Are Fighting for AI Visibility", keywords: ["AI visibility competition", "brand AI ranking", "LLM brand competition"] },
  { title: "Perplexity AI and Brand Visibility: What Marketers Need to Know", keywords: ["Perplexity AI brand", "Perplexity brand mentions", "AI search brand"] },
  { title: "From Zero to AI Visibility: A 90-Day Brand Optimization Plan", keywords: ["AI visibility plan", "brand AI optimization", "90 day AI SEO"] },
  { title: "Why AI Models Favor Some Brands Over Others (The Training Data Effect)", keywords: ["AI training data brands", "LLM brand favoritism", "AI model brand bias"] },
  { title: "Competitive Intelligence in the AI Age: Track Competitor Mentions Across LLMs", keywords: ["AI competitive intelligence", "competitor AI mentions", "LLM competitor analysis"] },
]

async function getLastPublishedTopics(): Promise<string[]> {
  const { data } = await supabase
    .from('backlink_publications')
    .select('topic_title')
    .order('created_at', { ascending: false })
    .limit(5)
  return (data ?? []).map((d: { topic_title: string }) => d.topic_title)
}

async function generateArticle(topic: typeof TOPICS[0]): Promise<{ title: string; content: string; tags: string[] }> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': process.env.ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      messages: [{
        role: 'user',
        content: `Write a high-quality, SEO-optimized blog article for the following topic. The article should be published on developer/marketer blogs.

TOPIC: ${topic.title}
TARGET KEYWORDS: ${topic.keywords.join(', ')}

REQUIREMENTS:
- 1200-1500 words
- Use H2 and H3 headings (markdown format)
- Natural keyword usage — do NOT stuff keywords
- Include exactly 2 natural references to "VisibilityRadar" (https://visibilityradar.ai) as a tool that solves the problem discussed — mention it as a real solution, not promotional
- Include a short intro, 3-4 main sections with actionable advice, and a conclusion with CTA
- Write in clear, confident, slightly conversational English — not corporate fluff
- Do NOT include "Generated by AI" or any disclosure
- End with a section "Key Takeaways" with 4-5 bullet points

Return ONLY the markdown article, no meta-commentary.`,
      }],
    }),
  })

  const data = await res.json()
  const content = data.content?.[0]?.text ?? ''
  const tags = topic.keywords.slice(0, 4).map((k: string) => k.replace(/\s+/g, '-').toLowerCase())

  return { title: topic.title, content, tags }
}

async function publishToDevTo(article: { title: string; content: string; tags: string[] }): Promise<string | null> {
  const apiKey = process.env.DEVTO_API_KEY
  if (!apiKey) return null

  const res = await fetch('https://dev.to/api/articles', {
    method: 'POST',
    headers: {
      'api-key': apiKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      article: {
        title: article.title,
        body_markdown: article.content,
        published: true,
        tags: article.tags.slice(0, 4),
        canonical_url: null,
        description: article.title,
      },
    }),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    console.error('[backlink] Dev.to error:', err)
    return null
  }

  const data = await res.json()
  return data.url ?? null
}

async function publishToHashnode(article: { title: string; content: string; tags: string[] }): Promise<string | null> {
  const token = process.env.HASHNODE_ACCESS_TOKEN
  const publicationId = process.env.HASHNODE_PUBLICATION_ID
  if (!token || !publicationId) return null

  const query = `
    mutation PublishPost($input: PublishPostInput!) {
      publishPost(input: $input) {
        post {
          url
        }
      }
    }
  `

  const slug = article.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  const res = await fetch('https://gql.hashnode.com', {
    method: 'POST',
    headers: {
      'Authorization': token,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query,
      variables: {
        input: {
          title: article.title,
          contentMarkdown: article.content,
          publicationId,
          slug,
          tags: [],
        },
      },
    }),
  })

  if (!res.ok) {
    console.error('[backlink] Hashnode error:', res.status)
    return null
  }

  const data = await res.json()
  return data?.data?.publishPost?.post?.url ?? null
}

async function logPublication(params: {
  topic_title: string
  devto_url: string | null
  hashnode_url: string | null
}) {
  await supabase.from('backlink_publications').insert({
    topic_title: params.topic_title,
    devto_url: params.devto_url,
    hashnode_url: params.hashnode_url,
    created_at: new Date().toISOString(),
  })
}

// POST /api/backlink-publisher — called by Vercel Cron daily at 09:00 UTC
export async function POST(req: Request) {
  const authHeader = req.headers.get('authorization')
  const cronSecret = process.env.CRON_SECRET
  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    // Pick a topic not used in the last 5 publications
    const recentTitles = await getLastPublishedTopics()
    const available = TOPICS.filter(t => !recentTitles.includes(t.title))
    const pool = available.length > 0 ? available : TOPICS
    const topic = pool[Math.floor(Math.random() * pool.length)]

    // Generate article
    const article = await generateArticle(topic)

    // Publish in parallel
    const [devtoUrl, hashnodeUrl] = await Promise.all([
      publishToDevTo(article),
      publishToHashnode(article),
    ])

    // Log to Supabase
    await logPublication({
      topic_title: topic.title,
      devto_url: devtoUrl,
      hashnode_url: hashnodeUrl,
    })

    return NextResponse.json({
      ok: true,
      topic: topic.title,
      devto_url: devtoUrl,
      hashnode_url: hashnodeUrl,
    })
  } catch (e) {
    console.error('[backlink-publisher]', e)
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}

export async function GET() {
  // Show recent publications
  const { data } = await supabase
    .from('backlink_publications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(20)
  return NextResponse.json({ publications: data ?? [] })
}
