import type { AnalyzeResponse } from "@/types";

const LOGO_TEXT = "VisibilityRadar";

// jsPDF built-in fonts only support WinAnsi — replace Turkish chars
function sanitize(str: string): string {
  return str
    .replace(/ş/g, "s").replace(/Ş/g, "S")
    .replace(/ğ/g, "g").replace(/Ğ/g, "G")
    .replace(/ü/g, "u").replace(/Ü/g, "U")
    .replace(/ö/g, "o").replace(/Ö/g, "O")
    .replace(/ı/g, "i").replace(/İ/g, "I")
    .replace(/ç/g, "c").replace(/Ç/g, "C")
    .replace(/â/g, "a").replace(/Â/g, "A")
    .replace(/î/g, "i").replace(/Î/g, "I")
    .replace(/û/g, "u").replace(/Û/g, "U")
    .replace(/[^\x00-\x7E]/g, "?");
}

const LABELS: Record<string, Record<string, string>> = {
  EN: {
    overallScore:    "Overall AI Score",
    modelScores:     "Per-Model Scores",
    competitorComp:  "Competitor Comparison",
    you:             "(you)",
    keyFindings:     "Key Findings",
    date:            "Date",
    brand:           "Brand",
    activeModels:    "Active Models",
    page:            "Page",
    actionSteps:     "Action Steps",
    generatedBy:     "Generated by Claude Opus 4.8",
    recommendations: "AI Visibility Recommendations",
    dashboardTitle:  "AI Visibility Analysis",
  },
  TR: {
    overallScore:    "Genel AI Skoru",
    modelScores:     "Model Bazli Skorlar",
    competitorComp:  "Rakip Karsilastirma",
    you:             "(sen)",
    keyFindings:     "Temel Bulgular",
    date:            "Tarih",
    brand:           "Marka",
    activeModels:    "Aktif Modeller",
    page:            "Sayfa",
    actionSteps:     "Aksiyon Adimlari",
    generatedBy:     "Claude Opus 4.8 tarafindan olusturuldu",
    recommendations: "AI Gorunurluk Onerileri",
    dashboardTitle:  "AI Gorunurluk Analizi",
  },
  DE: {
    overallScore:    "Gesamter KI-Score",
    modelScores:     "Scores je Modell",
    competitorComp:  "Wettbewerbsvergleich",
    you:             "(Sie)",
    keyFindings:     "Wichtigste Erkenntnisse",
    date:            "Datum",
    brand:           "Marke",
    activeModels:    "Aktive Modelle",
    page:            "Seite",
    actionSteps:     "Massnahmen",
    generatedBy:     "Generiert von Claude Opus 4.8",
    recommendations: "KI-Sichtbarkeitsempfehlungen",
    dashboardTitle:  "KI-Sichtbarkeitsanalyse",
  },
};

function getLang(market?: string) {
  if (market === "TR") return LABELS.TR;
  if (market === "DE") return LABELS.DE;
  return LABELS.EN;
}

function hexToRgb(hex: string): [number, number, number] {
  return [parseInt(hex.slice(1,3),16), parseInt(hex.slice(3,5),16), parseInt(hex.slice(5,7),16)];
}

function drawWatermark(doc: import("jspdf").jsPDF, pageWidth: number, pageHeight: number) {
  doc.saveGraphicsState();
  // @ts-expect-error GState typing
  doc.setGState(new doc.GState({ opacity: 0.05 }));
  doc.setFontSize(56);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40, 40, 40);
  doc.text(LOGO_TEXT, pageWidth / 2, pageHeight / 2, { align: "center", angle: 330 });
  doc.restoreGraphicsState();
}

function drawLogo(doc: import("jspdf").jsPDF, x: number, y: number, fontSize = 16) {
  doc.setFontSize(fontSize);
  doc.setFont("helvetica", "bold");
  // "Visibility" in dark slate, "Radar" in indigo — matches UI header
  doc.setTextColor(15, 23, 42);
  doc.text("Visibility", x, y);
  const visW = doc.getTextWidth("Visibility");
  doc.setTextColor(99, 102, 241);
  doc.text("Radar", x + visW, y);
  doc.setTextColor(15, 23, 42);
}

function drawHeader(doc: import("jspdf").jsPDF, pageWidth: number, subtitle: string) {
  doc.setFillColor(250, 251, 252);
  doc.rect(0, 0, pageWidth, 24, "F");
  drawLogo(doc, 12, 15, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(130, 130, 130);
  doc.text(sanitize(subtitle), pageWidth - 12, 15, { align: "right" });
  doc.setDrawColor(220, 220, 220);
  doc.line(0, 24, pageWidth, 24);
}

function drawFooter(doc: import("jspdf").jsPDF, pageWidth: number, pageHeight: number, pageNum: number) {
  const L = getLang();
  doc.setDrawColor(220, 220, 220);
  doc.line(12, pageHeight - 14, pageWidth - 12, pageHeight - 14);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(170, 170, 170);
  doc.text(`${L.page} ${pageNum}`, pageWidth / 2, pageHeight - 6, { align: "center" });
  doc.text("VisibilityRadar", 12, pageHeight - 6);
  doc.text(new Date().toLocaleDateString("en-GB"), pageWidth - 12, pageHeight - 6, { align: "right" });
}

function scoreBar(
  doc: import("jspdf").jsPDF, x: number, y: number,
  width: number, score: number, label: string, height = 5
) {
  const color: [number,number,number] = score >= 60 ? [52,211,153] : score >= 30 ? [251,191,36] : [239,68,68];
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(x, y, width, height, 2, 2, "F");
  const fillW = Math.max(3, (score / 100) * width);
  doc.setFillColor(...color);
  doc.roundedRect(x, y, fillW, height, 2, 2, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  doc.text(sanitize(label), x, y - 2);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...color);
  doc.text(`${score.toFixed(0)}`, x + width + 4, y + height - 0.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
}

function initPage(doc: import("jspdf").jsPDF, pageWidth: number, pageHeight: number, subtitle: string) {
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  drawWatermark(doc, pageWidth, pageHeight);
  drawHeader(doc, pageWidth, subtitle);
}

export async function exportDashboardPdf(data: AnalyzeResponse, market = "global") {
  const { jsPDF } = await import("jspdf");
  const L = getLang(market);
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 32;
  let page = 1;
  const subtitle = `${sanitize(data.brand)} — ${L.dashboardTitle}`;

  function addPage() {
    doc.addPage();
    page++;
    initPage(doc, pageWidth, pageHeight, subtitle);
    drawFooter(doc, pageWidth, pageHeight, page);
    y = 32;
  }

  function checkY(needed = 20) {
    if (y + needed > pageHeight - 20) addPage();
  }

  initPage(doc, pageWidth, pageHeight, subtitle);
  drawFooter(doc, pageWidth, pageHeight, page);

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text(L.dashboardTitle, 12, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 110, 110);
  doc.text(`${L.brand}: ${sanitize(data.brand)}`, 12, y);
  y += 5;
  doc.text(`${L.activeModels}: ${data.active_models.map(m => m.toUpperCase()).join(", ")}`, 12, y);
  y += 5;
  doc.text(`${L.date}: ${new Date().toLocaleDateString("en-GB", { year:"numeric", month:"long", day:"numeric" })}`, 12, y);
  y += 8;

  doc.setDrawColor(230, 230, 230);
  doc.line(12, y, pageWidth - 12, y);
  y += 10;

  // Overall score
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text(L.overallScore, 12, y);
  y += 8;

  const sc = data.overall_score;
  const scoreColor: [number,number,number] = sc >= 60 ? [52,211,153] : sc >= 30 ? [251,191,36] : [239,68,68];
  doc.setFontSize(40);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...scoreColor);
  doc.text(`${sc.toFixed(0)}`, 12, y + 10);
  doc.setFontSize(16);
  doc.setTextColor(160, 160, 160);
  doc.text("/ 100", 12 + doc.getTextWidth(`${sc.toFixed(0)}`) + 3, y + 10);
  y += 22;

  // Per-model scores
  checkY(16 + Object.keys(data.model_scores).length * 14);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text(L.modelScores, 12, y);
  y += 8;

  Object.entries(data.model_scores).forEach(([model, score]) => {
    checkY(14);
    scoreBar(doc, 12, y, pageWidth - 55, score, model.toUpperCase());
    y += 12;
  });
  y += 4;

  // Competitor comparison
  if (Object.keys(data.competitor_scores).length > 0) {
    checkY(20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 20);
    doc.text(L.competitorComp, 12, y);
    y += 8;

    checkY(14);
    scoreBar(doc, 12, y, pageWidth - 55, data.overall_score, `${sanitize(data.brand)} ${L.you}`);
    y += 12;

    Object.entries(data.competitor_scores).forEach(([name, s]) => {
      checkY(14);
      scoreBar(doc, 12, y, pageWidth - 55, s.overall, sanitize(name));
      y += 12;
    });
    y += 4;
  }

  // Insights
  checkY(20);
  doc.setDrawColor(230, 230, 230);
  doc.line(12, y, pageWidth - 12, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text(L.keyFindings, 12, y);
  y += 7;

  data.insights.forEach((insight) => {
    const lines = doc.splitTextToSize(`- ${sanitize(insight)}`, pageWidth - 28);
    checkY(lines.length * 5 + 4);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(lines, 15, y);
    y += lines.length * 5 + 4;
  });

  doc.save(`VisibilityRadar_${sanitize(data.brand)}_${Date.now()}.pdf`);
}

export async function exportRecommendationsPdf(
  brand: string,
  recommendations: {
    title: string;
    priority: string;
    category: string;
    description: string;
    actions: string[];
  }[],
  market = "global"
) {
  const { jsPDF } = await import("jspdf");
  const L = getLang(market);
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 32;
  let page = 1;
  const subtitle = `${sanitize(brand)} — ${L.recommendations}`;

  function addPage() {
    doc.addPage();
    page++;
    initPage(doc, pageWidth, pageHeight, subtitle);
    drawFooter(doc, pageWidth, pageHeight, page);
    y = 32;
  }

  function checkY(needed = 20) {
    if (y + needed > pageHeight - 20) addPage();
  }

  initPage(doc, pageWidth, pageHeight, subtitle);
  drawFooter(doc, pageWidth, pageHeight, page);

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text(L.recommendations, 12, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 110, 110);
  doc.text(`${L.brand}: ${sanitize(brand)}  |  ${recommendations.length} items  |  ${L.generatedBy}`, 12, y);
  y += 5;
  doc.text(`${L.date}: ${new Date().toLocaleDateString("en-GB", { year:"numeric", month:"long", day:"numeric" })}`, 12, y);
  y += 10;

  doc.setDrawColor(230, 230, 230);
  doc.line(12, y, pageWidth - 12, y);
  y += 10;

  const PRIORITY_COLOR: Record<string, [number,number,number]> = {
    high: [239,68,68], medium: [251,191,36], low: [148,163,184],
  };
  const PRIORITY_LABEL: Record<string, string> = { high: "High", medium: "Medium", low: "Low" };
  const CATEGORY_LABEL: Record<string, string> = {
    content: "Content", platform: "Platform", seo: "SEO", pr: "PR",
  };

  recommendations.forEach((rec, i) => {
    const pColor = PRIORITY_COLOR[rec.priority] ?? [148,163,184];
    const pLabel = PRIORITY_LABEL[rec.priority] ?? rec.priority;
    const catLabel = CATEGORY_LABEL[rec.category] ?? rec.category;
    const descLines = doc.splitTextToSize(sanitize(rec.description), pageWidth - 36);
    const actionLineCount = rec.actions.reduce((acc, a) => {
      return acc + doc.splitTextToSize(sanitize(a), pageWidth - 38).length;
    }, 0);
    const blockHeight = 8 + 5 + descLines.length * 5 + 6 + actionLineCount * 5 + 10;

    checkY(blockHeight);

    // Card bg
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(12, y - 4, pageWidth - 24, blockHeight, 3, 3, "F");
    doc.setDrawColor(220, 220, 220);
    doc.roundedRect(12, y - 4, pageWidth - 24, blockHeight, 3, 3, "S");

    // Priority color left bar
    doc.setFillColor(...pColor);
    doc.roundedRect(12, y - 4, 4, blockHeight, 2, 2, "F");

    // Number + title
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 20);
    doc.text(`${i + 1}. ${sanitize(rec.title)}`, 22, y + 3);

    // Priority badge
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...pColor);
    doc.text(pLabel, pageWidth - 40, y + 3);
    doc.setTextColor(140, 140, 140);
    doc.setFont("helvetica", "normal");
    doc.text(catLabel, pageWidth - 18, y + 3);
    y += 8;

    // Description
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(70, 70, 70);
    doc.text(descLines, 22, y);
    y += descLines.length * 5 + 5;

    // Actions header
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 100);
    doc.text(L.actionSteps + ":", 22, y);
    y += 5;

    // Actions
    rec.actions.forEach((action, j) => {
      const aLines = doc.splitTextToSize(`${j + 1}. ${sanitize(action)}`, pageWidth - 38);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 55, 55);
      doc.text(aLines, 26, y);
      y += aLines.length * 5;
    });

    y += 10;
  });

  doc.save(`VisibilityRadar_Recommendations_${sanitize(brand)}_${Date.now()}.pdf`);
}

// Alias used by RecommendationsPanel — model_scores param accepted but not printed in this layout
export async function generateRecommendationsPdf(
  brand: string,
  _overall_score: number,
  market: string,
  _model_scores: Record<string, number>,
  recommendations: { title: string; priority: string; category: string; description: string; actions: string[] }[]
) {
  return exportRecommendationsPdf(brand, recommendations, market);
}
